services:
  traefik:
    image: "traefik:v3.1.1"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.network=mikrus"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    networks:
      mikrus:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`traefik.mleczko.dev`)
      - traefik.http.routers.mydashboard.priority=1000
      - traefik.http.routers.mydashboard.service=api@internal
      - traefik.http.routers.mydashboard.middlewares=myauth
      - traefik.http.routers.mydashboard.entrypoints=websecure
      - traefik.http.routers.mydashboard.tls=true
      - traefik.http.middlewares.myauth.basicauth.users=traefik_dashboard:$$apr1$$WDcJUsnl$$E5lccC1C9kbO7i2NPg8mO.

  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./.docker/caddy/sites:/etc/caddy/sites
      - ./.docker/caddy/config:/etc/caddy/config
      - ./domains:/domains
    networks:
      mikrus:
      default:
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.caddy.rule=HostRegexp(`.+\.mleczko\.dev`) || Host(`porin.pl`) || Host(`www.porin.pl`) || Host(`marionetkamody.pl`) || Host(`mlecznarodzina.com`)
      - traefik.http.routers.caddySecure.rule=HostRegexp(`.+\.mleczko\.dev`) || Host(`porin.pl`) || Host(`www.porin.pl`) || Host(`marionetkamody.pl`) || Host(`mlecznarodzina.com`)
      - traefik.http.routers.caddySecure.entrypoints=websecure
      - traefik.http.routers.caddySecure.tls=true

  php83:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      target: php83
    restart: unless-stopped
    volumes:
      - ./domains:/domains
    networks:
      mikrus:
      default:

  php74:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      target: php74
    restart: unless-stopped
    volumes:
      - ./domains:/domains
    networks:
      mikrus:
      default:

  sftp:
    image: atmoz/sftp
    restart: unless-stopped
    command: adrian:$$1$$4SI.VeZo$$gY8AzHV4Hxr7TdWOMKWsx1:e:1001
    ports:
      - "30115:22"
    volumes:
      - ./domains/porin.pl:/home/adrian/porin.pl

networks:
  mikrus:
    external: true
